=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/exit_point_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="qualified">

	<!-- The definition of simple elements. -->
	<xs:element type="xs:string" name="qualifiedname" />
	<xs:element type="xs:string" name="methodname" />

	<!-- The definition of attributes. -->
	<xs:attribute name="id">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([0-9]+)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([a-zA-Z0-9.]+)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="rules">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([-]{0,1}[0-9]+)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<!-- The definition of complex elements. -->
	<xs:element name="parameters">
		<xs:complexType>
			<xs:attribute ref="type" use="required" />
			<xs:attribute ref="rules" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="exitpoint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="qualifiedname" />
				<xs:element ref="methodname" />
				<xs:element ref="parameters" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="id" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- The root element. -->
	<xs:element name="exitpoints">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="exitpoint" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/http_response_splitting.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- ANYTHING_IS_VALID(1), SANITIZED(2), LITERAL(4), STRING_CONCATENATION(8); -->

	<!-- javax.servlet.http.HttpServletResponse -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[javax.servlet.http.HttpServletResponse]]></qualifiedname>
		<methodname>sendRedirect</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<!-- javax.servlet.ServletContext -->
	<exitpoint id="02">
		<qualifiedname><![CDATA[javax.servlet.ServletContext]]></qualifiedname>
		<methodname>getRequestDispatcher</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/ldap_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[javax.naming.directory.InitialDirContext]]></qualifiedname>
		<methodname>InitialDirContext</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname><![CDATA[javax.naming.directory.InitialDirContext]]></qualifiedname>
		<methodname>search</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname><![CDATA[javax.naming.directory.InitialDirContext]]></qualifiedname>
		<methodname>search</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname><![CDATA[javax.naming.directory.InitialDirContext]]></qualifiedname>
		<methodname>search</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="05">
		<qualifiedname><![CDATA[javax.naming.directory.SearchControls]]></qualifiedname>
		<methodname>setReturningAttributes</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname><![CDATA[com.novell.ldap.LDAPConnection]]></qualifiedname>
		<methodname>connect</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="07">
		<qualifiedname><![CDATA[com.novell.ldap.LDAPConnection]]></qualifiedname>
		<methodname>search</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="08">
		<qualifiedname><![CDATA[com.novell.ldap.LDAPConnection]]></qualifiedname>
		<methodname>search</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/path_traversal.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->
	<!-- java.io -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[java.io.File]]></qualifiedname>
		<methodname>File</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname><![CDATA[java.io.File]]></qualifiedname>
		<methodname>File</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname><![CDATA[java.io.RandomAccessFile]]></qualifiedname>
		<methodname>RandomAccessFile</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname><![CDATA[java.io.FileReader]]></qualifiedname>
		<methodname>FileReader</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="05">
		<qualifiedname><![CDATA[java.io.FileInputStream]]></qualifiedname>
		<methodname>FileInputStream</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname><![CDATA[java.io.FileWriter]]></qualifiedname>
		<methodname>FileWriter</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="07">
		<qualifiedname><![CDATA[java.io.FileWriter]]></qualifiedname>
		<methodname>FileWriter</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="08">
		<qualifiedname><![CDATA[java.io.FileOutputStream]]></qualifiedname>
		<methodname>FileOutputStream</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="09">
		<qualifiedname><![CDATA[java.io.FileOutputStream]]></qualifiedname>
		<methodname>FileOutputStream</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- java.lang.Class -->
	<exitpoint id="10">
		<qualifiedname><![CDATA[java.lang.Class]]></qualifiedname>
		<methodname>getResource</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="11">
		<qualifiedname><![CDATA[java.lang.Class]]></qualifiedname>
		<methodname>getResourceAsStream</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<!-- javax.mail.internet.InternetAddress -->
	<exitpoint id="12">
		<qualifiedname><![CDATA[javax.mail.internet.InternetAddress]]></qualifiedname>
		<methodname>InternetAddress</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="13">
		<qualifiedname><![CDATA[javax.mail.internet.InternetAddress]]></qualifiedname>
		<methodname>parse</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/reflection_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->
	<!-- java.lang.Class -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[java.lang.Class]]></qualifiedname>
		<methodname>forName</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname><![CDATA[java.lang.Class]]></qualifiedname>
		<methodname>forName</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname><![CDATA[java.lang.Class(<[A-Za-z0-9_]*>)?]]></qualifiedname>
		<methodname>getField</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname><![CDATA[java.lang.Class(<[A-Za-z0-9_]*>)?]]></qualifiedname>
		<methodname>getMethod</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="05">
		<qualifiedname><![CDATA[java.lang.Class(<[A-Za-z0-9_]*>)?]]></qualifiedname>
		<methodname>getDeclaredField</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname><![CDATA[java.lang.Class(<[A-Za-z0-9_]*>)?]]></qualifiedname>
		<methodname>getDeclaredMethod</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/log_forging.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- ANYTHING_IS_VALID(1), SANITIZED(2), LITERAL(4), STRING_CONCATENATION(8); -->

	<!-- java.io.PrintStream -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[java.io.PrintStream]]></qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname><![CDATA[java.io.PrintStream]]></qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname><![CDATA[java.io.PrintStream]]></qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname><![CDATA[java.io.PrintStream]]></qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<!-- java.util.logging.Logger -->
	<exitpoint id="05">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>config</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>fine</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="07">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>finer</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="08">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>finest</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="09">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>info</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="10">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>warning</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="11">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>severe</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="12">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>entering</methodname>
		<parameters type="java.lang.String" rules="6" />
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="13">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>entering</methodname>
		<parameters type="java.lang.String" rules="6" />
		<parameters type="java.lang.String" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="14">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>log</methodname>
		<parameters type="java.util.logging.Level" rules="6" />
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="15">
		<qualifiedname><![CDATA[java.util.logging.Logger]]></qualifiedname>
		<methodname>log</methodname>
		<parameters type="java.util.logging.Level" rules="6" />
		<parameters type="java.lang.String" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<!-- org.apache.commons.logging.Log -->
	<exitpoint id="16">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>debug</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="17">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>debug</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="18">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>error</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="19">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>error</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="20">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>fatal</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="21">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>fatal</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="22">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>info</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="23">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>info</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="24">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>trace</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="25">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>trace</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="26">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>warn</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="27">
		<qualifiedname><![CDATA[org.apache.commons.logging.Log]]></qualifiedname>
		<methodname>warn</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<!-- java.io.BufferedWriter -->
	<exitpoint id="28">
		<qualifiedname><![CDATA[java.io.BufferedWriter]]></qualifiedname>
		<methodname>write</methodname>
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<exitpoint id="29">
		<qualifiedname><![CDATA[java.io.BufferedWriter]]></qualifiedname>
		<methodname>write</methodname>
		<parameters type="java.lang.String" rules="6" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- javax.servlet.ServletContext -->
	<exitpoint id="30">
		<qualifiedname><![CDATA[javax.servlet.ServletContext]]></qualifiedname>
		<methodname>log</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="31">
		<qualifiedname><![CDATA[javax.servlet.ServletContext]]></qualifiedname>
		<methodname>log</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
	<!-- javax.servlet.GenericServlet -->
	<exitpoint id="32">
		<qualifiedname><![CDATA[javax.servlet.GenericServlet]]></qualifiedname>
		<methodname>log</methodname>
		<parameters type="java.lang.String" rules="6" />
	</exitpoint>
	<exitpoint id="33">
		<qualifiedname><![CDATA[javax.servlet.GenericServlet]]></qualifiedname>
		<methodname>log</methodname>
		<parameters type="java.lang.Object" rules="6" />
		<parameters type="java.lang.Object" rules="6" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/cookie_poisoning.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->
	<!-- javax.servlet.http.Cookie -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[javax.servlet.http.Cookie]]></qualifiedname>
		<methodname>Cookie</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname><![CDATA[javax.servlet.http.Cookie]]></qualifiedname>
		<methodname>Cookie</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname><![CDATA[javax.servlet.http.Cookie]]></qualifiedname>
		<methodname>setComment</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname><![CDATA[javax.servlet.http.Cookie]]></qualifiedname>
		<methodname>setDomain</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="05">
		<qualifiedname><![CDATA[javax.servlet.http.Cookie]]></qualifiedname>
		<methodname>setPath</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname><![CDATA[javax.servlet.http.Cookie]]></qualifiedname>
		<methodname>setValue</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/cross_site_scripting.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->
	<!-- java.io.PrintWriter -->
	<exitpoint id="01">
		<qualifiedname>java.io.PrintWriter</qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname>java.io.PrintWriter</qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname>java.io.PrintWriter</qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname>java.io.PrintWriter</qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- java.io.PrintStream -->
	<exitpoint id="05">
		<qualifiedname>java.io.PrintStream</qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname>java.io.PrintStream</qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="07">
		<qualifiedname>java.io.PrintStream</qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="08">
		<qualifiedname>java.io.PrintStream</qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- javax.servlet.ServletOutputStream -->
	<exitpoint id="09">
		<qualifiedname>javax.servlet.ServletOutputStream</qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="10">
		<qualifiedname>javax.servlet.ServletOutputStream</qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<!-- javax.servlet.jsp.JspWriter -->
	<exitpoint id="11">
		<qualifiedname>javax.servlet.jsp.JspWriter</qualifiedname>
		<methodname>print</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="12">
		<qualifiedname>javax.servlet.jsp.JspWriter</qualifiedname>
		<methodname>println</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<!-- javax.servlet.http.HttpServletRequest -->
	<exitpoint id="13">
		<qualifiedname>javax.servlet.(http.Http)?ServletRequest</qualifiedname>
		<methodname>setAttribute</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="14">
		<qualifiedname>javax.servlet.(http.Http)?ServletRequest</qualifiedname>
		<methodname>setCharacterEncoding</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<!-- javax.servlet.http.HttpServletResponse -->
	<exitpoint id="15">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>sendError</methodname>
		<parameters type="java.lang.Object" rules="-1" />
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="16">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>setDateHeader</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="-1" />
	</exitpoint>
	<exitpoint id="17">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>addDateHeader</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="-1" />
	</exitpoint>
	<exitpoint id="18">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>setHeader</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="19">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>addHeader</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="20">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>setIntHeader</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="-1" />
	</exitpoint>
	<exitpoint id="21">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>addIntHeader</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="-1" />
	</exitpoint>
	<!-- javax.servlet.ServletResponse -->
	<exitpoint id="22">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>setCharacterEncoding</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="23">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>setContentType</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/command_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->
	<!-- java.lang.Runtime -->
	<exitpoint id="01">
		<qualifiedname>java.lang.Runtime</qualifiedname>
		<methodname>exec</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname>java.lang.Runtime</qualifiedname>
		<methodname>exec</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname>java.lang.Runtime</qualifiedname>
		<methodname>exec</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
</exitpoints>
