=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/exit_point_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="qualified">

	<!-- The definition of simple elements. -->
	<xs:element type="xs:string" name="qualifiedname" />
	<xs:element type="xs:string" name="methodname" />

	<!-- The definition of attributes. -->
	<xs:attribute name="id">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([0-9]+)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([a-zA-Z0-9.]+)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:attribute name="rules">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="([-]{0,1}[0-9]+)" />
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

	<!-- The definition of complex elements. -->
	<xs:element name="parameters">
		<xs:complexType>
			<xs:attribute ref="type" use="required" />
			<xs:attribute ref="rules" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="exitpoint">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="qualifiedname" />
				<xs:element ref="methodname" />
				<xs:element ref="parameters" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute ref="id" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- The root element. -->
	<xs:element name="exitpoints">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="exitpoint" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/xpath_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->
	<!-- javax.xml.xpath.XPath -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[javax.xml.xpath.XPath]]></qualifiedname>
		<methodname>compile</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname><![CDATA[javax.xml.xpath.XPath]]></qualifiedname>
		<methodname>evaluate</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname><![CDATA[javax.xml.xpath.XPath]]></qualifiedname>
		<methodname>evaluate</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname><![CDATA[javax.xml.xpath.XPathExpression]]></qualifiedname>
		<methodname>evaluate</methodname>
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="05">
		<qualifiedname><![CDATA[javax.xml.xpath.XPathExpression]]></qualifiedname>
		<methodname>evaluate</methodname>
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- org.apache.xpath.XPath -->
	<exitpoint id="04">
		<qualifiedname><![CDATA[org.apache.xpath.XPath]]></qualifiedname>
		<methodname>XPath</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="05">
		<qualifiedname><![CDATA[org.apache.xpath.XPath]]></qualifiedname>
		<methodname>XPath</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname><![CDATA[org.apache.xpath.XPath]]></qualifiedname>
		<methodname>XPath</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- org.apache.commons.jxpath.JXPath -->
	<exitpoint id="07">
		<qualifiedname><![CDATA[org.apache.commons.jxpath.JXPath]]></qualifiedname>
		<methodname>getValue</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<!-- org.xmldb.api.modules.XPathQueryService -->
	<exitpoint id="08">
		<qualifiedname><![CDATA[org.xmldb.api.modules.XPathQueryService]]></qualifiedname>
		<methodname>query</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<exitpoint id="09">
		<qualifiedname><![CDATA[org.xmldb.api.modules.XPathQueryService]]></qualifiedname>
		<methodname>query</methodname>
		<parameters type="java.lang.String" rules="1" />
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<!-- org.xmldb.api.modules.XMLResource -->
	<exitpoint id="10">
		<qualifiedname><![CDATA[org.xmldb.api.modules.XMLResource]]></qualifiedname>
		<methodname>setContent</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/unvalidated_redirecting.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- -1 Anything is valid. -->
	<!-- 0 Only sanitized values are valid. -->
	<!-- 1 LITERAL and sanitized values are valid. -->
	<!-- X1;X2;... These are the accepted values. -->

	<!-- javax.servlet.http.HttpServletResponse -->
	<exitpoint id="01">
		<qualifiedname>javax.servlet.(http.Http)?ServletResponse</qualifiedname>
		<methodname>sendRedirect</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
	<!-- javax.servlet.ServletContext -->
	<exitpoint id="02">
		<qualifiedname>javax.servlet.ServletContext</qualifiedname>
		<methodname>getRequestDispatcher</methodname>
		<parameters type="java.lang.String" rules="1" />
	</exitpoint>
</exitpoints>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/exit_point/sql_injection.xml
<?xml version="1.0" encoding="UTF-8"?>
<exitpoints xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="exit_point_schema.xsd">
	<!-- ANYTHING_IS_VALID(1), SANITIZED(2), LITERAL(4), STRING_CONCATENATION(8); -->

	<!-- java.sql.(Prepared)?Statement -->
	<exitpoint id="01">
		<qualifiedname><![CDATA[java.sql.(Prepared)?Statement]]></qualifiedname>
		<methodname>addBatch</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="02">
		<qualifiedname><![CDATA[java.sql.(Prepared)?Statement]]></qualifiedname>
		<methodname>execute</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="03">
		<qualifiedname><![CDATA[java.sql.(Prepared)?Statement]]></qualifiedname>
		<methodname>execute</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="04">
		<qualifiedname><![CDATA[java.sql.(Prepared)?Statement]]></qualifiedname>
		<methodname>executeQuery</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="05">
		<qualifiedname><![CDATA[java.sql.(Prepared)?Statement]]></qualifiedname>
		<methodname>executeUpdate</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="06">
		<qualifiedname><![CDATA[java.sql.(Prepared)?Statement]]></qualifiedname>
		<methodname>executeUpdate</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- java.sql.Connection -->
	<exitpoint id="07">
		<qualifiedname><![CDATA[java.sql.Connection]]></qualifiedname>
		<methodname>prepareStatement</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="08">
		<qualifiedname><![CDATA[java.sql.Connection]]></qualifiedname>
		<methodname>prepareStatement</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="09">
		<qualifiedname><![CDATA[java.sql.Connection]]></qualifiedname>
		<methodname>prepareCall</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="10">
		<qualifiedname><![CDATA[java.sql.Connection]]></qualifiedname>
		<methodname>prepareCall</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<exitpoint id="11">
		<qualifiedname><![CDATA[java.sql.Connection]]></qualifiedname>
		<methodname>prepareCall</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
		<parameters type="java.lang.Object" rules="1" />
	</exitpoint>
	<!-- javax.persistence.EntityManager -->
	<exitpoint id="12">
		<qualifiedname><![CDATA[javax.persistence.EntityManager]]></qualifiedname>
		<methodname>createNativeQuery</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="13">
		<qualifiedname><![CDATA[javax.persistence.EntityManager]]></qualifiedname>
		<methodname>createNativeQuery</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="14">
		<qualifiedname><![CDATA[javax.persistence.EntityManager]]></qualifiedname>
		<methodname>createQuery</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<!-- org.hibernate.Session 3x -->
	<!-- net.sf.hibernate.Session 2x -->
	<exitpoint id="15">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>createSQLQuery</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="16">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>createQuery</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="17">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>find</methodname>
		<parameters type="java.lang.String" rules="14" />
	</exitpoint>
	<exitpoint id="18">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>find</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="19">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>delete</methodname>
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="20">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>delete</methodname>
		<parameters type="java.lang.String" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="21">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>save</methodname>
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="22">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>save</methodname>
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="23">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>save</methodname>
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="24">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>saveOrUpdate</methodname>
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="25">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>update</methodname>
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="26">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>update</methodname>
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="27">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>load</methodname>
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
	<exitpoint id="28">
		<qualifiedname><![CDATA[(org|net.sf).hibernate.Session]]></qualifiedname>
		<methodname>load</methodname>
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
		<parameters type="java.lang.Object" rules="14" />
	</exitpoint>
</exitpoints>
