=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/resolution/resolution_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">

 <!-- The definition of simple elements. -->

 <!-- The definition of attributes. -->
 <xs:attribute name="type">
  <xs:simpleType>
   <xs:restriction base="xs:string">
    <xs:pattern value="([a-zA-Z0-9._]+)" />
   </xs:restriction>
  </xs:simpleType>
 </xs:attribute>

 <!-- The definition of complex elements. -->
 <xs:element name="label">
  <xs:simpleType>
   <xs:restriction base="xs:string">
    <xs:whiteSpace value="collapse" />
   </xs:restriction>
  </xs:simpleType>
 </xs:element>
 <xs:element name="description">
  <xs:simpleType>
   <xs:restriction base="xs:string">
    <xs:whiteSpace value="collapse" />
   </xs:restriction>
  </xs:simpleType>
 </xs:element>

 <xs:element name="resolution">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="label" />
    <xs:element ref="description" />
   </xs:sequence>
   <xs:attribute ref="type" use="required" />
  </xs:complexType>
 </xs:element>

 <!-- The root element. -->
 <xs:element name="resolutions">
  <xs:complexType>
   <xs:sequence>
    <xs:element ref="resolution" maxOccurs="unbounded" />
   </xs:sequence>
  </xs:complexType>
 </xs:element>

</xs:schema>

=== YoungLeeTAMUSA/TCM_Plugin/TCM_Plugin/knowledge_base/resolution/resolution.xml
<?xml version="1.0" encoding="UTF-8"?>
<resolutions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resolution_schema.xsd">
	<resolution type="1">
		<label><![CDATA[CommandInjectionResolution]]></label>
		<description>
		  <![CDATA[The full path: %s
      If you think this is a false positive you can ignore it.]]>
		</description>
	</resolution>
	<resolution type="2">
		<label><![CDATA[CookiePoisoningResolution]]></label>
		<description><![CDATA[CookiePoisoningResolution]]></description>
	</resolution>
	<resolution type="3"> <!-- CrossSiteScriptingResolution -->
		<label><![CDATA[Sanitize this element using OWASP libraries]]></label>
		<description><![CDATA[This element should be sanitized to avoid Cross-Site Scripting(XSS).<br/>
		Cross-Site Scripting (XSS) attacks are a type of injection, in which malicious scripts are injected into otherwise benign and trusted web sites.]]></description>
	</resolution>
	<resolution type="4">
		<label><![CDATA[PathTraversalResolution]]></label>
		<description><![CDATA[PathTraversalResolution]]></description>
	</resolution>
	<resolution type="5">
		<label><![CDATA[SecurityMisconfigurationResolution]]></label>
		<description><![CDATA[SecurityMisconfigurationResolution]]></description>
	</resolution>
	<resolution type="6">
		<label><![CDATA[SQLInjectionResolution]]></label>
		<description><![CDATA[SQLInjectionResolution]]></description>
	</resolution>
	<resolution type="7">
		<label><![CDATA[UnvalidatedRedirectingResolution]]></label>
		<description><![CDATA[UnvalidatedRedirectingResolution]]></description>
	</resolution>
	<resolution type="8">
		<label><![CDATA[Ignore this warning]]></label>
		<description>
		<![CDATA[
Our heuristics detected that <b>%s</b> might be vulnerable.<br/>
It has the full path: <b>%s</b><br/>
If you think it is a false positive you can ignore it and this warning will no longer appear.]]>
		</description>
	</resolution>
</resolutions>
